data1 <- read.table("household_power_consumption.txt",header = T, sep = ";")
names <- colnames(data1)
data <- read.table("household_power_consumption.txt",header = T, sep = ";", skip = 66636, nrows = 2880,na.strings = "?", col.names = names)
hist(data[,3],xlab = "Global Active Power (kilowatts)", main = "Global Active Power", col = "red")
dev.copy(png, file = "plot1.png", width = 480, height = 480, units = "px")
dev.off()