data <- read.table("household_power_consumption.txt",header = T, sep = ";")
names <- colnames(data)
data <- read.table("household_power_consumption.txt",header = T, sep = ";", skip = 66636, nrows = 2880, col.names = names)
data$DT <- strptime(paste(data[,1], data[,2]), "%d/%m/%Y %H:%M:%S")
plot(data$DT, data[,7], type = "n", xlab = "", ylab = "Energy sub metering")
lines(data$DT, data[,7], col ="black")
lines(data$DT, data[,8], col = "red")
lines(data$DT, data[,9], col = "blue")
legend("topright", lty = "solid", col = c("black", "red", "blue"), legend = c("Sub_metering_1     ", "Sub_metering_2     ", "Sub_metering_3     "))
dev.copy(png, "plot3.png", width = 480, height = 480, units = "px")
dev.off()